[package]
name = "respond_sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
tokio = {version = "1.15.0", features = ["full"] }
select = "0.5.0"
url = "2.2.2"